### ISSUE TITLE
Contao 4.13 Unterstützung

### ISSUE THREAD

**Issue by dp-designpilot** [terminal42/contao-image-delete#1]
Hallo

Könnt Ihr die Erweiterung zu 4.13 kompatibel machen ??

`Problem 1
    - terminal42/contao-image-delete[1.0.0, ..., 1.0.4] require doctrine/dbal ^2.11 -> found doctrine/dbal[2.11.0, ..., 2.13.7] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires terminal42/contao-image-delete ^1.0 -> satisfiable by terminal42/contao-image-delete[1.0.0, ..., 1.0.4].`

Freundliche Grüsse
designpilot

**Comment by aschempp** [comment]
Fixed in f2363ec11ebb43454051b5796097860756cd9022
